# Generated by Django 2.1.2 on 2019-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mquiz',
            name='qans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mquiz',
            name='qimg',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='mquiz',
            name='qhint',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mquiz',
            name='qop3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mquiz',
            name='qop4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mquiz',
            name='qop5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mquiz',
            name='qsol',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
