# Generated by Django 2.2.4 on 2020-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190310_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='mquiz',
            name='qimage',
            field=models.ImageField(blank=True, null=True, upload_to='mquiz/'),
        ),
    ]
