# Generated by Django 2.2.4 on 2020-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mquiz_qimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mquiz',
            name='qhimg',
            field=models.ImageField(blank=True, null=True, upload_to='mquiz/'),
        ),
        migrations.AddField(
            model_name='mquiz',
            name='qsimg',
            field=models.ImageField(blank=True, null=True, upload_to='mquiz/'),
        ),
    ]
